package org.firstinspires.ftc.teamcode.vegamind.Lifter;

public enum TransferState {
    NONE,
    HORIZONTAL_LIFTER_CLAW_TO_240,
    RETRACT_HORIZONTAL_LIFT,
    HORIZONTAL_LIFTER_CLAW_TO_270,
    RETRACT_VERTICAL_LIFT,
    RAM_HORIZONTAL_LIFT,
    TRANSFER_TO_VERTICAL_LIFTER_CLAW,
    EXTEND_HORIZONTAL_LIFTER,
    RAISE_VERTICAL_LIFTER,
    SWING_VERTICAL_LIFTER_ARM,
    RELEASE_VERTICAL_LIFTER_CLAW,
}
